/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package firstone;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yousef
 */
public class inadmin extends javax.swing.JFrame {

    /**
     * Creates new form inadmin
     */
    public inadmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        refreshsubjecttable();
        refreshstudenttable();


    }
        public void refreshstudenttable()
        {
            try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bfcai", "root", "root");
          PreparedStatement stat = con.prepareStatement("select * from student");
          ResultSet set = stat.executeQuery();
          DefaultTableModel dm =new DefaultTableModel();
          dm.addColumn("student ID");
          dm.addColumn("student name");
          dm.addColumn("student level");
          dm.addColumn("GPA");
          dm.addColumn("course id");
          
          while (set.next()) {
            String r[]={set.getString(1) , set.getString(2) , set.getString(3) , set.getString(4) , set.getString(5)};
            dm.addRow(r);
            
        }
          studenttable.setModel(dm);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "error in database");
        }
        }
        public void refreshsubjecttable()
    {
                try{
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bfcai", "root", "root");
          PreparedStatement stat = con.prepareStatement("select * from subjects");
          ResultSet set = stat.executeQuery();
          DefaultTableModel dm =new DefaultTableModel();
          dm.addColumn("sub id");
          dm.addColumn("sub name");
          dm.addColumn("sub teacher");
          dm.addColumn("maximum degree");
          dm.addColumn("minimum degree");
          
          while (set.next()) {
            String r[]={set.getString(1) , set.getString(2) , set.getString(3) , set.getString(4) , set.getString(5)};
            dm.addRow(r);
            
        }
          subjectstable.setModel(dm);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "error in database");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectstable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        subjectidfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        subjectnamefield = new javax.swing.JTextField();
        subjectteacherfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        maximumdegreefield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        minimumdegreefield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studenttable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        student_id_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        student_name_field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        student_gpa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        course_id = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        student_level_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subjectstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        subjectstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subjectstable);

        jLabel1.setText("subject id");

        jLabel2.setText("subject name");

        jLabel3.setText("subject teacher");

        subjectnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectnamefieldActionPerformed(evt);
            }
        });

        jLabel4.setText("maximum degree");

        jLabel5.setText("minimum degree");

        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("show values");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subjectnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subjectteacherfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maximumdegreefield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minimumdegreefield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectidfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(subjectnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(subjectteacherfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maximumdegreefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(minimumdegreefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("التعديل علي المواد", jPanel1);

        studenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        studenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studenttableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(studenttable);

        jLabel6.setText("student ID");

        jLabel7.setText("student name");

        jLabel8.setText("GPA");

        jLabel9.setText("subject ID");

        jButton5.setText("show values");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("insert");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel10.setText("student level");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(student_id_field)
                            .addComponent(student_name_field)
                            .addComponent(student_gpa)
                            .addComponent(course_id)
                            .addComponent(student_level_field, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(student_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_level_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(student_gpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("التعديل علي الطلاب", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectnamefieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                try{
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bfcai", "root", "root");
          PreparedStatement stat = con.prepareStatement("insert into subjects(subid,subname,subteach,maxdeg,mindeg)values(?,?,?,?,?)");
          int id =Integer.valueOf( subjectidfield.getText());
          String supname = subjectnamefield.getText();
          String supteach = subjectteacherfield.getText();
          int maxdeg =Integer.valueOf( maximumdegreefield.getText());
          int mindeg =Integer.valueOf(minimumdegreefield.getText());
          stat.setInt(1, id);
          stat.setString(2, supname);
          stat.setString(3, supteach);
          stat.setInt(4, maxdeg);
          stat.setInt(5, mindeg);
          stat.executeUpdate();
          subjectidfield.setText("");
          subjectnamefield.setText("");
          subjectteacherfield.setText("");
          maximumdegreefield.setText("");
          minimumdegreefield.setText("");
          jButton3ActionPerformed(evt);
          JOptionPane.showMessageDialog(this, "insertion success");

                  }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "error in database");
        }
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        try{
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bfcai", "root", "root");
          PreparedStatement stat = con.prepareStatement("select * from subjects");
          ResultSet set = stat.executeQuery();
          DefaultTableModel dm =new DefaultTableModel();
          dm.addColumn("sub id");
          dm.addColumn("sub name");
          dm.addColumn("sub teacher");
          dm.addColumn("maximum degree");
          dm.addColumn("minimum degree");
          
          while (set.next()) {
            String r[]={set.getString(1) , set.getString(2) , set.getString(3) , set.getString(4) , set.getString(5)};
            dm.addRow(r);
            
        }
          subjectstable.setModel(dm);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "error in database");
        }
          
          
          
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void subjectstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectstableMouseClicked
        int row_num = subjectstable.getSelectedRow();
        String id = subjectstable.getValueAt(row_num, 0).toString();      
        String subname = subjectstable.getValueAt(row_num, 1).toString();
        String subteach = subjectstable.getValueAt(row_num, 2).toString();
        String maxdeg = subjectstable.getValueAt(row_num, 3).toString();
        String minideg = subjectstable.getValueAt(row_num, 4).toString();
        subjectidfield.setText(id);
        subjectnamefield.setText(subname);
        subjectteacherfield.setText(subteach);
        maximumdegreefield.setText(maxdeg);
        minimumdegreefield.setText(minideg);// TODO add your handling code here:
    }//GEN-LAST:event_subjectstableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bfcai", "root", "root");
          PreparedStatement stat = con.prepareStatement("update subjects set subname=?,subteach=?,maxdeg=?,mindeg=? where subid=?");
          int id =Integer.valueOf( subjectidfield.getText());
          String supname = subjectnamefield.getText();
          String supteach = subjectteacherfield.getText();
          int maxdeg =Integer.valueOf( maximumdegreefield.getText());
          int mindeg =Integer.valueOf(minimumdegreefield.getText());
          stat.setInt(5, id);
          stat.setString(1, supname);
          stat.setString(2, supteach);
          stat.setInt(3, maxdeg);
          stat.setInt(4, mindeg);
          stat.executeUpdate();
          subjectidfield.setText("");
          subjectnamefield.setText("");
          subjectteacherfield.setText("");
          maximumdegreefield.setText("");
          minimumdegreefield.setText("");
          jButton3ActionPerformed(evt);
          JOptionPane.showMessageDialog(this, "update success");

                  }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "error in database");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               try{
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bfcai", "root", "root");
          PreparedStatement stat = con.prepareStatement("delete from subjects where subid=?");
          int id =Integer.valueOf( subjectidfield.getText());
         
          stat.setInt(1, id);

          stat.executeUpdate();
          subjectidfield.setText("");
          subjectnamefield.setText("");
          subjectteacherfield.setText("");
          maximumdegreefield.setText("");
          minimumdegreefield.setText("");
          jButton3ActionPerformed(evt);
          JOptionPane.showMessageDialog(this, "update success");

                  }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "error in database");
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
               try{
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bfcai", "root", "root");
          PreparedStatement stat = con.prepareStatement("select * from student");
          ResultSet set = stat.executeQuery();
          DefaultTableModel dm =new DefaultTableModel();
          dm.addColumn("student ID");
          dm.addColumn("student name");
          dm.addColumn("student level");
          dm.addColumn("GPA");
          dm.addColumn("course id");
          
          while (set.next()) {
            String r[]={set.getString(1) , set.getString(2) , set.getString(3) , set.getString(4) , set.getString(5)};
            dm.addRow(r);
            
        }
          studenttable.setModel(dm);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "error in database");
        }
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void studenttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studenttableMouseClicked
        int row_num = studenttable.getSelectedRow();
        String id = studenttable.getValueAt(row_num, 0).toString();      
        String subname = studenttable.getValueAt(row_num, 1).toString();
        String studentlevel = studenttable.getValueAt(row_num, 2).toString();
        String subteach = studenttable.getValueAt(row_num, 3).toString();
        String maxdeg = studenttable.getValueAt(row_num, 4).toString();
        student_id_field.setText(id);
        student_name_field.setText(subname);
        student_level_field.setText(studentlevel);
        student_gpa.setText(subteach);
        course_id.setText(maxdeg);
    }//GEN-LAST:event_studenttableMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   try{
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bfcai", "root", "root");
          PreparedStatement stat = con.prepareStatement("insert into student(studentid,studentname,studentlevel,gpa,subid)values(?,?,?,?,?)");
          int id =Integer.valueOf( student_id_field.getText());
          String studentname = student_name_field.getText();
          String studentlevel = student_name_field.getText();
          double gpa =Double.valueOf( student_gpa.getText());
          int courseid =Integer.valueOf(course_id.getText());
          stat.setInt(1, id);
          stat.setString(2, studentname);
          stat.setString(3, studentlevel);
          stat.setDouble(4, gpa);
          stat.setInt(5, courseid);
          stat.executeUpdate();
          student_gpa.setText("");
          student_id_field.setText("");
          student_level_field.setText("");
          student_name_field.setText("");
          course_id.setText("");
          jButton5ActionPerformed(evt);
          JOptionPane.showMessageDialog(this, "insertion success");

                  }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "error in database");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            try{
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bfcai", "root", "root");
          PreparedStatement stat = con.prepareStatement("update student set studentname=?,studentlevel=?,gpa=?,subid=? where studentid=?");
          int id =Integer.valueOf( student_id_field.getText());
          String studentname = student_name_field.getText();
          String studentlevel = student_level_field.getText();
          double gpa =Double.valueOf( student_gpa.getText());
          int supid =Integer.valueOf(course_id.getText());
          stat.setInt(5, id);
          stat.setString(1, studentname);
          stat.setString(2, studentlevel);
          stat.setDouble(3, gpa);
          stat.setInt(4, supid);
          stat.executeUpdate();
          student_id_field.setText("");
          student_name_field.setText("");
          student_level_field.setText("");
          student_gpa.setText("");
          course_id.setText("");
          jButton5ActionPerformed(evt);
          JOptionPane.showMessageDialog(this, "update success");

                  }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "error in database");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
     try{
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bfcai", "root", "root");
          PreparedStatement stat = con.prepareStatement("delete from student where studentid=?");
          int id =Integer.valueOf( student_id_field.getText());
         
          stat.setInt(1, id);

          stat.executeUpdate();
          student_id_field.setText("");
          student_name_field.setText("");
          student_level_field.setText("");
          student_gpa.setText("");
          course_id.setText("");
          jButton5ActionPerformed(evt);
          JOptionPane.showMessageDialog(this, "update success");

                  }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "error in database");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField course_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField maximumdegreefield;
    private javax.swing.JTextField minimumdegreefield;
    private javax.swing.JTextField student_gpa;
    private javax.swing.JTextField student_id_field;
    private javax.swing.JTextField student_level_field;
    private javax.swing.JTextField student_name_field;
    private javax.swing.JTable studenttable;
    private javax.swing.JTextField subjectidfield;
    private javax.swing.JTextField subjectnamefield;
    private javax.swing.JTable subjectstable;
    private javax.swing.JTextField subjectteacherfield;
    // End of variables declaration//GEN-END:variables
}
